### ISSUE TITLE
circe-generic-extras 0.14.3 not published

### ISSUE THREAD

**Issue by augi** [circe/circe-generic-extras#242]
There is `0.14.3` version of `circe` but the latest version of `circe-generic-extras` is still `0.14.2`. I believe we are not the only ones that version these artifacts together 🙏

**Comment by plokhotnyuk** [comment]
Also it would be great to have Scala Native support in this version as it is was added for core modules of circe in 0.14.3

**Comment by zarthross** [comment]
@plokhotnyuk Feel free to make a Issue for the scala native support.

@augi circe-generic and circe-generic-extras are completely different repos right now and other than keeping the minor versions in cadence for compatibility, and I do not plan on releasing patch versions with no changes going forward.

**Comment by augi** [comment]
@zarthross They are different repos but in the same organization, and the versioning has matched till now. So it IMHO makes sense that users used to version all the `circe*` dependencies together, and this is why I believe it would fix/improve the DevEx to keep the versioning in-sync, as long as possible 🙏

**Comment by zarthross** [comment]
We'll work on getting scala-native support, and we'll release once that's ready.

**Comment by zarthross** [comment]
@augi See #248

**Comment by zarthross** [comment]
@augi / @plokhotnyuk, https://github.com/circe/circe-generic-extras/releases/tag/v0.14.3
