### ISSUE TITLE
@JsonCodec(encodeOnly=true) causes a compiler error in Scala 2.13

### ISSUE THREAD

**Issue by leonardehrenfried** [circe/circe-generic-extras#3]
When upgrading from Scala 2.12 to 2.13 am running into the following compiler error:

```
Usage of named or default arguments transformed this annotation
[error] constructor call into a block. The corresponding AnnotationInfo
[error] will contain references to local values and default getters instead
[error] of the actual argument trees
[error]   @JsonCodec(decodeOnly = true)
[error]    ^
```
What is the correct way to express this in Scala 2.13?

Note that I have set my compiler options to very strict (https://github.com/DavidGregory084/sbt-tpolecat/blob/master/src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala) and all warnings (which this might be) are converted to errors.

**Comment by erwan** [comment]
For generic-extra that should be `@ConfiguredJsonCodec` now, to prevent confusion with the regular `@JsonCodec`.

What did you import?

**Comment by travisbrown** [comment]
Oh, sorry, didn't catch that this could be vanilla circe-generic.

**Comment by leonardehrenfried** [comment]
Oh yeah, I didn't notice either. 

For the record I imported `import io.circe.generic.JsonCodec`.

**Comment by leonardehrenfried** [comment]
I've reopened it here: https://github.com/circe/circe/issues/1264
