### ISSUE TITLE
Upgrade circe dependencies to version 0.14.6

### ISSUE THREAD

**Issue by awilliamsOM1** [circe/circe-generic-extras#330]
Circe has released new versions of their libraries 0.14.6. circe-generic-extras should upgrade the version used to allow organizations that use strict dependency checking to upgrade circe.

There is already a PR up to make this change. https://github.com/circe/circe-generic-extras/pull/312

This issue is not intended to dictate the version of circe-generic-extras used to release this change. The maintainers can choose the version number of circe-generic-extras that meets their release strategy.

**Comment by zarthross** [comment]
See: https://github.com/circe/circe-generic-extras/issues/279#issuecomment-1815013527
