### ISSUE TITLE
Upgrade circe to 0.14.7 and release corresponding versions

### ISSUE THREAD

**Issue by wb14123** [circe/circe-generic-extras#354]
I saw the newest circe dependency is upgraded to 0.14.6 but it hasn't been released to Maven central.

And can we upgrade circe to 0.14.7 as well? I saw there is an auto PR https://github.com/circe/circe-generic-extras/pull/350 but the ScalaJS build failed. I think we need to merge the PR to upgrade ScalaJS first: https://github.com/circe/circe-generic-extras/pull/348

**Comment by ag91** [comment]
hello, I see the dependencies have been bumped but there have been no releases of this repo after 0.14.3: what is blocking them? Somebody pressing the button?

**Comment by zarthross** [comment]
https://github.com/circe/circe-generic-extras/pull/361 when this is resolved we'll push a release.

**Comment by zarthross** [comment]
https://github.com/circe/circe-generic-extras/releases/tag/v0.14.4
