### ISSUE TITLE
Provide @implicitNotFound on derived codec classes

### ISSUE THREAD

**Issue by kubukoz** [circe/circe-generic-extras#56]
Hi! I just spent considerable time looking for a reason why a codec wasn't derived, and the root cause turned out to be the missing `sealed` keyword. As a way to avoid this happening for others, I would suggesting annotations like:

```scala
@implicitNotFound(
  """Could not found ConfiguredAsObjectCodec for type ${A}.
Some possible causes for this:
- ${A} isn't a case class or sealed trat
- some of ${A}'s members don't have codecs of their own"""
- missing implicit Configuration
)
```

to ConfiguredAsObjectCodec, EnumerationCodec, ReprAsObjectCodec, UnwrappedCodec and their encoder/decoder counterparts.

This also applies to circe-generic, although I'm using -extras more, so I'm starting here.

Let me know if this sounds like a good idea and I'll add these.

**Comment by travisbrown** [comment]
Sure, that'd be great!

**Comment by majk-p** [comment]
I've just issued a PR to fix that: https://github.com/circe/circe-generic-extras/pull/57
